"""empty message

Revision ID: c8c2aae059e9
Revises: f5e93efb06bd
Create Date: 2023-04-29 11:16:28.854536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c2aae059e9'
down_revision = 'f5e93efb06bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Pedidos', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Pedidos', 'status')
    # ### end Alembic commands ###
